{{- if .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookeo-mcp
  labels:
    app: bookeo-mcp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookeo-mcp
                port:
                  number: 8000
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: bookeo-mcp-tls-cert
{{- end }}
