apiVersion: v1
kind: Secret
metadata:
  name: bookeo-mcp
  labels:
    app: bookeo-mcp
type: Opaque
stringData:
  API_KEY: {{ .Values.bookeo.apiKey | quote }}
  API_SECRET: {{ .Values.bookeo.apiSecret | quote }}
